import Head from "next/head";

import { groq } from "next-sanity";

import { Post } from "@/types";

import Blogs from "@/components/Blogs";
import { client } from "@/client";

export interface PostProps {
  posts: Post[];
}

export const revalidate = 60;

const query = groq`*[_type == 'post']{
	...,
	author->,
	categories[]->,
  } | order(_createdAt desc)`;

export default function Home({ posts }: PostProps) {
  return (
    <>
      <Head>
        <title>Ini&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Blogs posts={posts} />
    </>
  );
}

export async function getStaticProps() {
  const posts = await client.fetch(query);

  return {
    props: { posts },
  };
}
